version: '3'

services:
  app-container:
    image: utm-app:1
    
    build:
      context: ./                                                
      dockerfile: Dockerfile        
    
    ports:
      - "9090:9090"                 